# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_os_config_os_policy_assignment'
generation_type: 'handwritten'
api_service_name: 'osconfig.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'OsPolicyAssignment'
